### ISSUE TITLE
Redirecting from previous version

### ISSUE THREAD

**Issue by moeenio** [WorldLanguages/ScratchStats.com#7]
Currently, doing a Qwant search for "scratch stats" shows the old version in results, which just, doesn't work anymore. Maybe putting a redirect/link on the old site ?

**Comment by WorldLanguages** [comment]
Thanks for creating an issue, ScratchStats.com should be indexed correctly now and I'm working on improvements to other search related features/issues.

**Comment by moeenio** [comment]
How have you done that ?
